### ISSUE TITLE
afterRender threw an error in 'markup://c:ESignature' [h.afterRender is not a function]

### ISSUE THREAD

**Issue by mingworld** [david-onehub-dev/lightning-esignature#1]
Hi,
I encountered this error when using this component.
afterRender threw an error in 'markup://c:ESignature' [h.afterRender is not a function]
Failing descriptor: {markup://c:ESignature}

It will be good if you can have a look at this issue.

Great lightning component and thanks for sharing it.

Ming

**Comment by david-onehub-dev** [comment]
just remove rerender.js. we donot need it

On Oct 10, 2017 6:33 AM, Ming Ma <notifications@github.com> wrote:

Hi,
I encountered this error when using this component.
afterRender threw an error in 'markup://c:ESignature' [h.afterRender is not a function]
Failing descriptor: {markup://c:ESignature}

It will be good if you can have a look at this issue.

Great lightning component and thanks for sharing it.

Ming
